FROM python:3.11-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y \
    chromium \
    xorg \
    xvfb \
    dbus-x11 \
    --no-install-recommends

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . .

# Set up the virtual display
ENV DISPLAY=:99
ENV USE_LOCALSTACK=true

RUN chmod +x /app/entrypoint.sh

EXPOSE 8080

# Command to run the FastAPI application
#CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]
ENTRYPOINT ["./entrypoint.sh"]